name: request_mapper
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  http_parser: ^4.0.2
  mime: ^1.0.5
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
